macro.inc fixed, introducing sfx macros, several NZ0 functions
Xeeynamo/sotn-decomp pull request #27
Opened 2022-11-18 23:44 UTC by sonicdcer

2022-11-19 02:10 UTC, Xeeynamo requested changes
Nice macro fix! The only thing I ask is to delete `SotnObjects` as those objects are already found in `stages.h`.

2022-11-19 06:49 UTC, sonicdcer commented
> Nice macro fix! The only thing I ask is to delete `SotnObjects` as those objects are already found in `stages.h`.

Are you talking about these?
// Those entity IDs are common across all stages
#define ENTITY_BREAKABLE 1
#define ENTITY_EXPLOSION 2
#define ENTITY_ITEM_DROP 3
#define ENTITY_NUMERIC_DAMAGE 4
#define ENTITY_RED_DOOR 5
#define ENTITY_INTENSE_EXPLOSION 6
#define ENTITY_ABSORB_ORB 7
#define ENTITY_ROOM_FOREGROUND 8
#define ENTITY_STAGE_NAME_POPUP 9
#define ENTITY_HEART_DROP 10
#define ENTITY_RELIC 11
#define ENTITY_COLLECTABLE 12
#define ENTITY_ENEMY_BLOOD 13
#define ENTITY_UNKNOWN_0D 14

2022-11-19 11:39 UTC, Xeeynamo commented
> > Nice macro fix! The only thing I ask is to delete `SotnObjects` as those objects are already found in `stages.h`.
> 
> Are you referring to these? because i couldn't find anything else. I don't think these are object IDs but if they are, i think they should be in hex and inside an enum, as they are almost guaranteed to be mixed in logical comparisons, in addition to be consecutive.
> 
> // Those entity IDs are common across all stages #define ENTITY_BREAKABLE 1 #define ENTITY_EXPLOSION 2 #define ENTITY_ITEM_DROP 3 #define ENTITY_NUMERIC_DAMAGE 4 #define ENTITY_RED_DOOR 5 #define ENTITY_INTENSE_EXPLOSION 6 #define ENTITY_ABSORB_ORB 7 #define ENTITY_ROOM_FOREGROUND 8 #define ENTITY_STAGE_NAME_POPUP 9 #define ENTITY_HEART_DROP 10 #define ENTITY_RELIC 11 #define ENTITY_COLLECTABLE 12 #define ENTITY_ENEMY_BLOOD 13 #define ENTITY_UNKNOWN_0D 14

yes

2022-11-25 17:51 UTC, Xeeynamo approved these changes

2022-11-25 17:51 UTC, merged