DRA DebugCaptureScreen, DebugCaptureVideo
Xeeynamo/sotn-decomp pull request #330
Opened 2023-07-07 16:20 UTC by Xeeynamo

Matches the two orphan functions `DebugCaptureScreen` and `DebugCaptureVideo`. I also fully imported the `.rodata` into `42398.c` and I am proud to say the file is now fully decompiled! I also renamed two other functions that are used by the two I decompiled. They are now all fully documented. Note the unused `u8 bmp[0x100];` in `DebugCaptureVideo`, probably a copy&pasta left-over. The function does not match without it.

I am waiting for https://github.com/mkst/maspsx/pull/6 and https://github.com/mkst/maspsx/pull/7 to be merged as currently maspsx breaks the two functions.

2023-07-09 00:13 UTC, sonicdcer requested changes

2023-07-09 00:13 UTC, sonicdcer commented on src/dra/42398.c
> +void DebugCaptureVideo(void) {
I think this should be DebugCaptureDemo, a video is something different. I'm assuming this was used to capture the strategy demos for defeating the bosses? That's what japan devs usually call Demos.

2023-07-10 17:38 UTC, sonicdcer approved these changes

2023-07-11 20:36 UTC, mkst commented
I have merged the 2 PRs into `maspsx` - thank you very much :)

2023-07-19 20:15 UTC, merged