DRE EntityCSMoveAlucard
Xeeynamo/sotn-decomp pull request #390
Opened 2023-07-23 16:32 UTC by sonicdcer

Had to declare D_80097400 before each function use because it needs to be a different type, may be part of a struct.

2023-07-23 16:39 UTC, sozud approved these changes
Looks good

2023-07-23 16:39 UTC, sozud commented on src/st/dre/14774.c
> +        if (g_Player.unk0C & 7) {
I tried a couple of simplifications here but they didn't match. This seems to be the scratch https://decomp.me/scratch/T8Auk

2023-07-23 18:08 UTC, Xeeynamo requested changes

2023-07-23 18:08 UTC, Xeeynamo commented on src/st/dre/14774.c
> +        if (g_DemoMode != Demo_None) {
```suggestion
        if (g_DemoMode != Demo_None) {
            self->ext.generic.unk7C.s = 64;
        } else {
            self->ext.generic.unk7C.s = 128;
        }
        break;
```

2023-07-23 18:08 UTC, Xeeynamo commented on src/st/dre/14774.c
> +                if (!(g_Player.unk0C & 1)) {
```suggestion
            if (g_blinkTimer & 1) {
                if (g_Player.unk0C & 1) {
                    g_Player.D_80072EF4 = 8;
                } else if (g_Player.unk0C & 2) {
                    g_Player.D_80072EF4 = 4;
                } else if (g_Player.unk0C & 4) {
                    g_Player.D_80072EF4 = 2;
                }
            }
```

2023-07-23 18:08 UTC, Xeeynamo commented on src/st/dre/14774.c
> +        if (AnimateEntity(D_80180944, self) == 0) {
```suggestion
        if (AnimateEntity(D_80180944, self) == 0) {
            SetStep(7);
        } else {
            player->animCurFrame = self->animCurFrame;
        }
        break;
```

2023-07-27 03:43 UTC, sozud commented
@Xeeynamo This one is waiting on figuring out a better solution for `D_80097400`, correct? I think you mentioned you wanted to take a look, did you have a chance yet?

2023-07-27 11:22 UTC, Xeeynamo commented
Correct, we need to find how that symbol is used and use it accordingly. I have not yet had the opportunity to dive into it yet.

2023-09-03 00:52 UTC, closed without merging