Decompile func_800E38CC
Xeeynamo/sotn-decomp pull request #58
Opened 2023-01-17 07:04 UTC by sozud

2023-01-17 09:11 UTC, Xeeynamo requested changes
Left some comments

2023-01-17 09:11 UTC, Xeeynamo commented on include/dra.h
> +extern s16 D_80136308;
This is an array of s16: `extern s16 D_80136308[]`

2023-01-17 09:11 UTC, Xeeynamo commented on src/dra/42398.c
> +            (s16) * (&D_80136308 + ((D_800A0158 + D_800A04F8)));
whenever you see `(&D_80012345 + something)` that is almost always rewritable as `D_80012345[something]`

2023-01-17 09:11 UTC, Xeeynamo commented on src/dra/42398.c
> +        D_800A0158 += 1;
can get rid of `+=1` for a simpler `++`

2023-01-17 09:11 UTC, Xeeynamo commented on src/dra/42398.c
> +        if ((u32)D_800A0158 >= 0x24U) {
Whenever possible, try getting rid of redundant casts to make the code leaner

2023-01-17 09:11 UTC, Xeeynamo commented on src/dra/42398.c
> +            return;
You can get rid of this return by using an `else`. I believe that is how developers wrote the real code.

2023-01-17 16:03 UTC, sozud commented
Thanks, I think the comments should be resolved now.

2023-01-20 02:59 UTC, Xeeynamo approved these changes
All good. Thank you for the contribution!

2023-01-20 02:59 UTC, merged