Decompile func_800FDD44
Xeeynamo/sotn-decomp pull request #59
Opened 2023-01-17 15:55 UTC by sozud

2023-01-17 16:09 UTC, sonicdcer requested changes
Good work!

2023-01-17 16:09 UTC, sonicdcer commented on src/dra/42398.c
> +}
```suggestion
bool func_800FDD44(s32 equipHeadIndex) {
    s32 equipedItem;
    u8 temp_s1;
    u8 temp_v0;

    equipedItem = player_equip_head[equipHeadIndex];
    temp_s1 = D_800A4B1D[player_equip_head[equipHeadIndex]].unk0;
    if (!(func_800FD7C0(0x54, 4))) {
        if (temp_s1 != 0) {
            temp_v0 = D_8009798A[equipedItem];
            if (temp_v0 == 0) {
                player_equip_head[equipHeadIndex] = 0;
                func_800F53A4();
                return true;
            }
            D_8009798A[equipedItem]--;
        }
    }
    return false;
}
```

2023-01-17 16:09 UTC, sonicdcer commented on include/dra.h
> +extern s8 D_800A4B1D[];
```suggestion
extern Unkstruct_800A4B12 D_800A4B1D[];
```

2023-01-20 03:00 UTC, Xeeynamo approved these changes
`player_equip_head[equipHeadIndex]` start to look sus. Probably that is that an equipment array of size 5. But so far this looks good!

2023-01-20 03:00 UTC, merged